name: tests

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Run the tests
        run: |
          pytest -s tests/

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
